### PR TITLE
Call XStream.processAnnotations

### PR DESCRIPTION
**Pull request by jglick**
Compatibility with https://github.com/jenkinsci/jenkins/pull/4944.

### CODE REVIEW

**Review by jansohn — APPROVED** [review]

**Comment by jglick** [comment]
Do you plan to release this?

**Comment by jansohn** [comment]
Thanks for the reminder! I just released a new version...

**Comment by jglick** [comment]
Great! By the way you did something weird with Release Drafter or `maven-release-plugin`: https://github.com/jenkinsci/deploy-plugin/tags shows both `1.16` and `deploy-1.16`. Normally `deploy-1.16` would be the tag generated by the release, and you use that tag in R.D. for a release of whatever name you like (such as `1.16`).

**Comment by jansohn** [comment]
Yeah, thanks, already saw that myself. Cleaned it up and should be fine now, I think...

**Pull request merged**
