### PR TITLE
JENKINS-24876: Parameterized Tomcat, JBoss, and GlassFish adapters (Tomc...

### PR DESCRIPTION
**Pull request by asmith34**
...at and JBoss - usernmae and url, GlassFish - username, home, port, and hostname).

### CODE REVIEW

**Comment by acyriac** [comment]
any updates on this PR. This is a much needed enhancement

**Comment by martinnirtl** [comment]
What about this PR?

**Comment by chenrui333** [comment]
+1

**Comment by ric79** [comment]
Nice!

**Comment by ric79** [comment]
I'm a newbie. 
May I ask if this new release will be also available from Jenkins Upload Center or I need to manually install that master release?

**Comment by chenrui333** [comment]
@ric79 Checkout the [deploy plugin wiki](https://wiki.jenkins-ci.org/display/JENKINS/Deploy+Plugin), it should go to the next release. The last one was June 2.

**Comment by rompic** [comment]
july 2 2014?

**Comment by chenrui333** [comment]
I guess so, have not been released for a while

**Comment by chenrui333** [comment]
[changes since last release](https://github.com/jenkinsci/deploy-plugin/compare/deploy-1.10...master)

**Comment by ric79** [comment]
So, who is plugin owner? Can he provide un a release date? Just because I need to know if the plugin is still maintained..

**Comment by chenrui333** [comment]
@ric79 I think @olamy can answer your question.

**Comment by ric79** [comment]
@olamy  can you provide us a date for the release? I really need this feature
Thanks!

**Comment by ric79** [comment]
no answer?

**Pull request merged**
