### PR TITLE
[FIXED JENKINS-24876] Expand Tomcat server URL with build variables

### PR DESCRIPTION
**Pull request by vernyquartara**
"Tomcat URL" field in Tomcat Adapters is now parameterizable using build variable

### CODE REVIEW

**Comment by rsandell** [comment]
It is hard to do a code review when it looks like all the content on some files has changed completely even though they haven't.

Did you change file encoding or something?

**Comment by vernyquartara** [comment]
I think no... this isn't the first pull request I send. How can I fix this?

2015-01-12 13:04 GMT+01:00 Robert Sandell <notifications@github.com>:

> It is hard to do a code review when it looks like all the content on some
> files has changed completely even though they haven't.
>
> Did you change file encoding or something?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/jenkinsci/deploy-plugin/pull/17#issuecomment-69560724>
> .
>



-- 
Verny Quartara

**Comment by rsandell** [comment]
I don't know, it doesn't seem to be white space changes, GitHub usually highlights those, hence my guess on file encoding.

**Comment by vernyquartara** [comment]
Can be Eclipse's automatic code formatter. I doubt a change in encoding

**Comment by daniel-beck** [comment]
Line endings were changed.

**Comment by rsandell** [comment]
So almost a year and no changes to line endings yet. Can we close?

**Comment by vernyquartara** [comment]
It seem the issue has been solved, see this
<https://github.com/jenkinsci/deploy-plugin/commit/ce2fc7f51ba35f9854d1d683ec72b2079c436282>

Hence you can close. Thnak you

VQ



2015-12-08 12:58 GMT+01:00 Robert Sandell <notifications@github.com>:

> So almost a year and no changes to line endings yet. Can we close?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jenkinsci/deploy-plugin/pull/17#issuecomment-162861016>
> .
>



-- 
Verny Quartara

**Comment by vadipp** [comment]
Seems like actually the fix in ce2fc7f doesn't work. We are using "Deploy to container Plugin" v1.10 with Jenkins ver. 1.647. We are using a string parameter named SERVER and getting "java.net.UnknownHostException: ${SERVER}" during build.

**Comment by vadipp** [comment]
@frekele hi, would you mind to indicate whether a new fix was committed, or you closed the issue because of ce2fc7f ?

**Comment by frekele** [comment]
I closed by inactivity and was conflicting with the current code too.
Would you like to help us?

**Comment by vadipp** [comment]
Oh, sorry, didn't realize that it's a pull request, not an issue.

The issue is here https://issues.jenkins-ci.org/browse/JENKINS-24876 I suppose?

I can only help with reproducing and collecting logs, but not with actually fixing the code.

**Comment by frekele** [comment]
I think we need to make a refactoring, the current code in master branch is very dirty.

**Pull request closed without merging**
