### PR TITLE
[FIXED JENKINS-24275] Support for build parameters

### PR DESCRIPTION
**Pull request by laimoncijus**
Hi,

I've added support for using build parameters to be able to configure plugin to use values dynamically.

### CODE REVIEW

**Comment by MrGutFeeling** [comment]
I'd also like to see this included. I have a parameterised build where the parameter is used to choose which project from the repository will be built. It would be good to be able to use that same parameter to specify where that project's build gets deployed.

**Comment by pm-priyesh-potdar** [comment]
Waiting for this feature.

**Comment by acyriac** [comment]
any updates on this

**Comment by jdebois** [comment]
Any chance of these changes being pulled in? Very useful feature.

**Comment by ric79** [comment]
come on! this plugin has not updates since two years.

**Comment by jdebois** [comment]
I ended up just creating a shell step and issuing a curl command to transfer the artifacts:
curl -T foo-app.war 'http://{tomcat deployer username}:{tomcat deployer password}@{host}:{port}/manager/text/deploy?path=/foo-app&update=true'

**Comment by ric79** [comment]
@jdebois: Me too.

**Comment by frekele** [comment]
This code is broken, please fix to merge.

**Pull request closed without merging**
