### PR TITLE
added functionality to resolve parameter variable in war/ear name field

### PR DESCRIPTION
**Pull request by ivanstefko**
These changes gives ability to have war/ear field parametrized.

### CODE REVIEW

**Comment by ivanstefko** [comment]
Hi frekele,
    OK, no problem but can't see any conflicts there. Which kind of conflict are you supposed to be resolved? Organize imports?

**Comment by frekele** [comment]
```
<<<<<<< master

            EnvVars envVars = new EnvVars();
            if (run instanceof AbstractBuild) {
                final AbstractBuild build = (AbstractBuild) run;
                envVars = build.getEnvironment(listener);
            }
            
            final VariableResolver<String> resolver = new VariableResolver.ByMap<String>(envVars);
            final String warFiles = Util.replaceMacro(envVars.expand(this.war), resolver); 

            FilePath[] wars = workspace.list(warFiles);
=======
            EnvVars environment = run.getEnvironment(listener);
            String expandedVar = Util.replaceMacro(war, environment);
            FilePath[] wars = workspace.list(expandedVar);
>>>>>>> master
```

**Comment by frekele** [comment]
I'm sorry ignore my comment.

**Comment by ivanstefko** [comment]
Thanks!
When do you plan to release new version with merged changes?

**Comment by frekele** [comment]
No plans yet, because the master branch is several errors.

**Comment by rompic** [comment]
I would also love to see a new release (including the pipeline capabilities)

**Comment by jansohn** [comment]
> 
> 
> No plans yet, because the master branch contains several errors.

@frekele I think I fixed the errors in the master branch. Please take a look at https://github.com/jenkinsci/deploy-plugin/pull/34. Hopefully we can get a new release out after merging that PR!

**Pull request merged**
