### PR TITLE
Adding tomcat 8 support

### PR DESCRIPTION
**Pull request by mattimus5460**
Updated cargo version to 1.4.8 and added a Tomcat 8x container adapter

### CODE REVIEW

**Comment by svivekkrishna** [comment]
Is this PR going to be merged into a release soon? Even though the Tomcat7 version works well with Tomcat8, it'd be really helpful to have a dedicated Tomcat8 support so as to avoid confusion while looking at the build logs. :-)

**Comment by chenrui333** [comment]
What is the status of this PR now?

**Comment by chenrui333** [comment]
@olamy Thanks a lot!

**Comment by rompic** [comment]
+1

**Comment by meeximum** [comment]
+1

**Comment by ISMAELMARTINEZ** [comment]
+1

**Comment by artk199** [comment]
+1

**Comment by riyuuli** [comment]
+1

**Comment by code4j-chen** [comment]
+1

**Comment by chenrui333** [comment]
Also the Tomcat 9 is getting more and more adoptions, we may need its support as well.

Thanks,

**Comment by camilolopes** [comment]
release for support tomcat 8 when are we going to release this plugin?

**Pull request merged**
