### PR TITLE
JENKINS-51440 Configure alternative context for each Tomcat container

### PR DESCRIPTION
**Pull request by motofix**
Following https://issues.jenkins-ci.org/browse/JENKINS-51440 enhancement request.

### CODE REVIEW

**Comment by motofix** [comment]
Hello, I do not understand why the ci check failed. Could you please give me a hint?

**Comment by alecharp** [comment]
@jenkinsci/code-reviewers can you please assign in the review of this PR?

**Comment by jansohn** [comment]
@frekele why did you close this? It would allowe users to configure a different context path which was requested several times in the issue tracker (JENKINS-3624/JENKINS-21187/JENKINS-51440).

@motofix please rebase on current master and then we can merge it.

**Comment by jansohn** [comment]
work done in #40

**Comment by jansohn** [comment]
Yes, please add it as an advanced option and add a help description for the new field.

**Pull request closed without merging**
